SYSROOT:=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk

include ../theos/makefiles/common.mk

TOOL_NAME = installer
installer_FILES = installer.mm
installer_INSTALL_PATH = /

include $(FW_MAKEDIR)/tool.mk
